/*
 * The MIT License
 *
 * Copyright 2018 Megan Leet (Zowayix).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ROMniscience.Handlers {
	class SegaCommon {

		public readonly static IDictionary<string, string> LICENSEES = new Dictionary<string, string> {
			{"SEGA", "Sega"}, //Interestingly enough
			{"ACLD", "Ballistic"},
			{"ASCI", "Asciiware"},
			{"RSI", "Razorsoft"},
			{"TREC", "Treco"},
			{"VRGN", "Virgin"},
			{"WSTN", "Westone"},
			//https://segaretro.org/Third-party_T-series_codes
			{"T-10", "Takara"},
			{"T-11", "Taito"},
			{"T-12", "Capcom"},
			{"T-13", "Data East"},
			{"T-14", "Namco"},
			{"T-15", "Sunsoft"},
			{"T-16", "Ma-Ba (Mattel + Bandai)"},
			{"T-17", "Dempa"},
			{"T-18", "Technosoft"},
			{"T-19", "Technosoft (19)"},
			{"T-20", "Asmik"},
			{"T-21", "ASCII"},
			{"T-22", "Micronet"},
			{"T-23", "VIC Tokai"},
			{"T-24", "Sammy (Treco)"}, //Another USA division that they used to publish some Genesis games
			{"T-25", "Nippon Computer Systems (Masaya)"},
			{"T-26", "Sigma"},
			{"T-27", "Toho"},
			{"T-28", "Hot-B"},
			{"T-29", "Kyugo"},
			{"T-30", "Video System"},
			{"T-31", "SNK"},
			{"T-32", "Wolf Team"},
			{"T-33", "Kaneko"},
			{"T-34", "Dreamworks"},
			{"T-35", "Seismic Software/Compile"},
			{"T-36", "Tecmo"},
			{"T-40", "Toaplan"},
			{"T-41", "UNIPACC"},
			{"T-42", "UFL"},
			{"T-43", "Human"},
			{"T-44", "Sanritsu"},
			{"T-45", "Game Arts"},
			{"T-46", "Kodansha"},
			{"T-47", "Sage's Creation"},
			{"T-48", "Tengen"},
			{"T-49", "Telenet"},
			{"T-50", "Electronic Arts"},
			{"T-51", "Microcabin"},
			{"T-52", "Systemsoft"},
			{"T-53", "Riverhillsoft"},
			{"T-54", "Face"},
			{"T-55", "Nuvision Entertainment"},
			{"T-56", "Razorsoft"},
			{"T-57", "Jaleco"},
			{"T-58", "Visco"},
			{"T-60", "Victor"},
			{"T-61", "Wonder Amusement Studio"},
			{"T-62", "Sony Imagesoft"},
			{"T-63", "Toshiba EMI"},
			{"T-64", "Information Global Service"},
			{"T-65", "Tsukuda Ideal"},
			{"T-66", "Compile"},
			{"T-67", "Home Data/Magical"},
			{"T-68", "CSK Research Institute"},
			{"T-69", "Arena"}, //nice
			{"T-70", "Virgin"},
			{"T-71", "Nihon Bussan (Nichibutsu)"},
			{"T-72", "Varie"},
			{"T-73", "Coconuts Japan or Soft Vision"},
			{"T-74", "Palsoft"},
			{"T-75", "Pony Canyon"},
			{"T-76", "Koei"},
			{"T-77", "Takeru/Sur De Wave"},
			{"T-79", "U.S. Gold"},
			{"T-81", "Acclaim"},
			{"T-83", "Gametek"},
			{"T-84", "Datawest"},
			{"T-85", "PCM Complete"},
			{"T-86", "Absolute"},
			{"T-87", "Mindscape"},
			{"T-88", "Domark"},
			{"T-89", "Parker Bros"},
			{"T-91", "Pack-in-Soft"},
			{"T-92", "Polydor"},
			{"T-93", "Sony"},
			{"T-95", "Konami"},
			{"T-97", "Midway/Tradewest/Williams"},
			{"T-99", "Success"},
			{"T-100", "THQ"},
			{"T-101", "Tecmagik"},
			{"T-102", "Samsung"}, //Used for Pico titles
			{"T-103", "Takara"},
			{"T-105", "Shogakukan"},
			{"T-106", "Electronic Arts Victor"},
			{"T-107", "Electro Brain"},
			{"T-109", "Saddleback Graphics"},
			{"T-110", "Dynamix"},
			{"T-111", "American Laser Games"},
			{"T-112", "Hi-Tech Expressions"},
			{"T-113", "Psygnosis"},
			{"T-114", "T&E Soft"},
			{"T-115", "Core Design"},
			{"T-118", "The Learning Company"},
			{"T-119", "Accolade"},
			{"T-120", "Codemasters"},
			{"T-121", "ReadySoft"},
			{"T-123", "Gremlin"},
			{"T-124", "Spectrum Holobyte"},
			{"T-125", "Interplay"},
			{"T-126", "Maxis"},
			{"T-127", "Working Designs"},
			{"T-130", "Activision"},
			{"T-132", "Playmates"},
			{"T-133", "Bandai"},
			{"T-135", "CapDisc"},
			{"T-137", "ASC Games"},
			{"T-139", "Viacom"},
			{"T-141", "Toei"},
			{"T-143", "Hudson Soft"},
			{"T-144", "Atlus"},
			{"T-145", "Sony"},
			{"T-146", "Takara"},
			{"T-147", "Sansan"},
			{"T-149", "Nisshouiwai Infocom"},
			{"T-150", "Imagineer"},
			{"T-151", "Infogrames"},
			{"T-152", "Davidson & Associates"},
			{"T-153", "Rocket Science Games"},
			{"T-154", "Technos Japan"},
			{"T-157", "Angel"},
			{"T-158", "Mindscape"},
			{"T-159", "Crystal Dynamics"},
			{"T-160", "Sales Curve"},
			{"T-161", "Fox"},
			{"T-162", "Digital Pictures"},
			{"T-164", "Ocean Software"},
			{"T-165", "Seta"},
			{"T-166", "Altron"},
			{"T-167", "ASK Kodansha"},
			{"T-168", "Athena"},
			{"T-169", "Gakken"},
			{"T-170", "General Entertainment"},
			{"T-174", "Glams"},
			{"T-176", "ASCII Something Good"},
			{"T-177", "Ubisoft"},
			{"T-178", "Hitachi"},
			{"T-180", "BMG"},
			{"T-181", "Obunsha"},
			{"T-182", "Thinking Cap"},
			{"T-185", "Gaga Communications"},
			{"T-186", "SoftBank"},
			{"T-187", "Naxat Soft"},
			{"T-188", "Mizuki"},
			{"T-189", "KAZe"},
			{"T-193", "Sega Yonezawa"},
			{"T-194", "We Net"},
			{"T-195", "Datam Polystar"},
			{"T-197", "KID"},
			{"T-198", "Epoch"},
			{"T-199", "Ving"},
			{"T-200", "Yoshimoto Kogyo"},
			{"T-201", "NEC Interchannel"},
			{"T-202", "Sonnet Computer Entertainment"},
			{"T-203", "Game Studio"},
			{"T-204", "Psikyo"},
			{"T-205", "Media Entertainment"},
			{"T-206", "Banpresto"},
			{"T-207", "Ecseco Development"},
			{"T-208", "Bullet-Proof Software"},
			{"T-209", "Sieg"},
			{"T-210", "Yanoman"},
			{"T-212", "Oz Club"},
			{"T-213", "Nihon Create"},
			{"T-214", "Media Rings Corporation"},
			{"T-215", "Shoeisha"},
			{"T-216", "OPeNBooK"},
			{"T-217", "Hakuhodo"},
			{"T-218", "Aroma"},
			{"T-219", "Societa Daikanyama"},
			{"T-220", "Arc System Works"},
			{"T-221", "Climax Entertainment"},
			{"T-222", "Pioneer LDC"},
			{"T-223", "Tokuma Shoten"},
			{"T-224", "I'MAX"},
			{"T-226", "Shogakukan"},
			{"T-227", "Vantan International"},
			{"T-229", "Titus"},
			{"T-230", "LucasArts"},
			{"T-231", "Pai"},
			{"T-232", "Ecole"},
			{"T-233", "Nayuta"},
			{"T-234", "Bandai Visual"},
			{"T-235", "Quintet"},
			{"T-239", "Disney"},
			{"T-240", "OpenBook9003"},
			{"T-241", "Multisoft"},
			{"T-242", "Sky Think System"},
			{"T-243", "OCC"},
			{"T-246", "Increment P"},
			{"T-249", "King Records"},
			{"T-250", "Fun House"},
			{"T-251", "Patra"},
			{"T-252", "Inner Brain"},
			{"T-253", "Make Software"},
			{"T-254", "GT Interactive"},
			{"T-255", "Kodansha"},
			{"T-257", "Clef"},
			{"T-259", "C-Seven"},
			{"T-260", "Fujitsu Parex"},
			{"T-261", "Xing Entertainment"},
			{"T-264", "Media Quest"},
			{"T-268", "Wooyoung System"},
			{"T-270", "Nihon System"},
			{"T-271", "Scholar"},
			{"T-273", "Datt Japan"},
			{"T-278", "MediaWorks"},
			{"T-279", "Kadokawa Shoten"},
			{"T-280", "Elf"},
			{"T-282", "Tomy"},
			{"T-289", "KSS"},
			{"T-290", "Mainichi Communications"},
			{"T-291", "Warashi"},
			{"T-292", "Metro"},
			{"T-293", "Sai-Mate"},
			{"T-294", "Kokopeli Digital Studios"},
			{"T-296", "Planning Office Wada (POW)"},
			{"T-297", "Telstar"},
			{"T-300", "Warp or Kumon Publishing"},
			{"T-303", "Masudaya"},
			{"T-306", "Soft Office"},
			{"T-307", "Empire Interactive"},
			{"T-308", "Genki"},
			{"T-309", "Neverland"},
			{"T-310", "Shar Rock"},
			{"T-311", "Natsume"},
			{"T-312", "Nexus Interact"},
			{"T-313", "Aplix Corporation"},
			{"T-314", "Omiya Soft"},
			{"T-315", "JVC"},
			{"T-316", "Zoom"},
			{"T-321", "TEN Institute"},
			{"T-322", "Fujitsu"},
			{"T-325", "TGL"},
			{"T-326", "Red Entertainment"},
			{"T-328", "Waka Manufacturing"},
			{"T-329", "Treasure"},
			{"T-330", "Tokuma Shoten Intermedia"},
			{"T-331", "Camelot"},
			{"T-339", "Sting"},
			{"T-340", "Chunsoft"},
			{"T-341", "Aki"},
			{"T-342", "From Software"},
			{"T-346", "Daiki"},
			{"T-348", "Aspect"},
			{"T-350", "Micro Vision"},
			{"T-351", "Gainax"},
			{"T-354", "FortyFive (45XLV)"},
			{"T-355", "Enix"},
			{"T-356", "Ray Corporation"},
			{"T-357", "Tonkin House"},
			{"T-360", "Outrigger"},
			{"T-361", "B-Factory"},
			{"T-362", "LayUp"},
			{"T-363", "Axela"},
			{"T-364", "WorkJam"},
			{"T-365", "Nihon Syscom"},
			{"T-367", "Full On Games"},
			{"T-368", "Eidos"},
			{"T-369", "UEP Systems"},
			{"T-370", "Shouei System"},
			{"T-371", "GMF"},
			{"T-373", "ADK"},
			{"T-374", "Softstar Entertainment"},
			{"T-375", "Nexton"},
			{"T-376", "Denshi Media Services"},
			{"T-379", "Takuyo"},
			{"T-380", "Starlight Marry"},
			{"T-381", "Crystal Vision"},
			{"T-382", "Kamata and Partners"},
			{"T-383", "AquaPlus"},
			{"T-384", "Media Gallop"},
			{"T-385", "Culture Brain"},
			{"T-386", "Locus"},
			{"T-387", "Entertainment Software Publishing"},
			{"T-388", "NEC"},
			{"T-390", "Pulse Interactive"},
			{"T-391", "Random House"},
			{"T-394", "Vivarium"},
			{"T-395", "Mebius"},
			{"T-396", "Panther Software"},
			{"T-397", "TBS"},
			{"T-398", "NetVillage"},
			{"T-400", "Vision"},
			{"T-401", "Shangri-La"},
			{"T-402", "Crave Entertainment"},
			{"T-403", "Metro3D"},
			{"T-404", "Majesco"},
			{"T-405", "Take-Two Interactive"},
			{"T-406", "Hasbro"},
			{"T-407", "Rage Games"},
			{"T-408", "Marvelous"},
			{"T-409", "Bottom Up"},
			{"T-410", "Daikoku Denki"},
			{"T-411", "Sunrise Interactive"},
			{"T-412", "Bimboosoft"},
			{"T-413", "UFO"},
			{"T-414", "Mattel"},
			{"T-415", "CaramelPot"},
			{"T-416", "Vatical Entertainment"},
			{"T-417", "Ripcord Games"},
			{"T-418", "Sega Toys"},
			{"T-419", "Gathering of Developers"},
			{"T-421", "Rockstar"},
			{"T-422", "Winkysoft"},
			{"T-423", "Cyberfront"},
			{"T-424", "DaZZ"},
			{"T-428", "Kobi"},
			{"T-429", "Fujicom"},
			{"T-433", "Real Vision"},
			{"T-434", "Visit"},
			{"T-435", "Global A Entertainment"},
			{"T-438", "Studio Wonder Effect"},
			{"T-439", "Media Factory"},
			{"T-441", "Red?"},
			{"T-443", "Agetec"},
			{"T-444", "Abel"},
			{"T-445", "Softmax"},
			{"T-446", "Isao"},
			{"T-447", "Kool Kizz"},
			{"T-448", "GeneX"},
			{"T-449", "Xicat Interactive"},
			{"T-450", "Swing! Entertainment"},
			{"T-451", "Yuke's"},
			{"T-454", "AAA Game"},
			{"T-455", "TV Asahi"},
			{"T-456", "Crazy Games"},
			{"T-457", "Atmark"},
			{"T-458", "Hackberry"},
			{"T-460", "AIA"},
			{"T-461", "Starfish-SD"},
			{"T-462", "Idea Factory"},
			{"T-463", "Broccoli"},
			{"T-465", "Oaks (Princess Soft)"},
			{"T-466", "Bigben Interactive"},
			{"T-467", "G.rev"},
			{"T-469", "Symbio Planning"},
			{"T-471", "Alchemist"},
			{"T-473", "SNK Playmore"},
			{"T-474", "D3Publisher"},
			{"T-475", "Rain Software"},
			{"T-476", "Good Navigate"},
			{"T-477", "Alfa System"},
			{"T-478", "Milestone"},
			{"T-479", "Triangle Service"},
		};
	}
}
